### ISSUE TITLE
`CreateTransactionError: Error: utxosList must contain at least 1 utxo`

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/wallet-lib#201]
Current Behavior
This error occurs when attempting to spend funds. It appears the account is undefined. However, the code has also executed correctly, so the problem is intermittent.
The code being executed is here:
https://github.com/dashmachine/autofaucet-express/blob/master/index.js

## Your Environment

Evonet 0.16

I am not sure if this is just #178 under a different guise??

Error output:
```
Something went wrong: TypeError: Cannot read property 'getUnusedAddress' of undefined
    at getDrip (/home/nigel/autofaucet-express/index.js:32:33)
    at /home/nigel/autofaucet-express/index.js:83:15
    at Layer.handle [as handle_request] (/home/nigel/autofaucet-express/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/autofaucet-express/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/nigel/autofaucet-express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/nigel/autofaucet-express/node_modules/express/lib/router/layer.js:95:5)
    at /home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:281:22
    at param (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:354:14)
    at param (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/nigel/autofaucet-express/node_modules/express/lib/router/index.js:410:3)
```

**Comment by dashameter** [comment]
@Alex-Werner is this bug expected to be closed with the upcoming v.21?

**Comment by SamKirby22** [comment]
Discussed in Triage - P1, Maverick to discuss with Alex.

**Comment by dash-maverick** [comment]
Won't make it for v21. But as a patch for v21 shortly after releasing the v21 - yes

**Comment by dash-maverick** [comment]
lets proceed with a retest

**Comment by dashameter** [comment]
@Alex-Werner I see a different error instead:
`InvalidRequestError: Transaction already in chain: Transaction already in block chain` even though not a single transaction has been successfully broadcast yet. Is this simply a different string for the same error or shall I we close this issue and open a new one ?

**Comment by thephez** [comment]
> @Alex-Werner I see a different error instead: `InvalidRequestError: Transaction already in chain: Transaction already in block chain` even though not a single transaction has been successfully broadcast yet. Is this simply a different string for the same error or shall I we close this issue and open a new one ?

@dashameter Do you have a TXID for the tx? It would probably be worth checking the chain to make sure it's not there in case a tx was somehow broadcast in spite of an error.

**Comment by dash-maverick** [comment]
@dashameter @SamKirby22 should be solved from now - please double check (have a look at https://github.com/dashevo/wallet-lib/issues/232)

**Comment by dashameter** [comment]
retest failed, the mnemonic of the `sendTx2.js` encounters a flood of these errors:

```
2|sendTx2  | Error: Merkle root from the diff doesn't match calculated merkle root after diff is applied
2|sendTx2  |     at SimplifiedMNList.applyDiff (/root/dash-dapp-autofaucet/node_modules/@dashevo/dashcore-lib/lib/deterministicmnlist/SimplifiedMNList.js:85:11)
2|sendTx2  |     at SimplifiedMasternodeListProvider.updateMasternodeList (/root/dash-dapp-autofaucet/node_modules/@dashevo/dapi-client/lib/SimplifiedMasternodeListProvider/SimplifiedMasternodeListProvider.js:59:29)
2|sendTx2  |     at runMicrotasks (<anonymous>)
2|sendTx2  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2|sendTx2  |     at async SimplifiedMasternodeListProvider.getSimplifiedMNList (/root/dash-dapp-autofaucet/node_modules/@dashevo/dapi-client/lib/SimplifiedMasternodeListProvider/SimplifiedMasternodeListProvider.js:34:7)
2|sendTx2  |     at async SimplifiedMasternodeListDAPIAddressProvider.getLiveAddress (/root/dash-dapp-autofaucet/node_modules/@dashevo/dapi-client/lib/dapiAddressProvider/SimplifiedMasternodeListDAPIAddressProvider.js:21:17)
2|sendTx2  |     at async GrpcTransport.request (/root/dash-dapp-autofaucet/node_modules/@dashevo/dapi-client/lib/transport/GrpcTransport/GrpcTransport.js:46:21)
2|sendTx2  |     at async CoreMethodsFacade.getTransaction (/root/dash-dapp-autofaucet/node_modules/@dashevo/dapi-client/lib/methods/core/getTransaction/getTransactionFactory.js:34:26)
2|sendTx2  |     at async DAPIClientTransport.getTransaction (/root/dash-dapp-autofaucet/node_modules/@dashevo/wallet-lib/src/transport/DAPIClientTransport/methods/getTransaction.js:16:22)
2|sendTx2  |     at async TransactionSyncStreamWorker.handleTransactionFromStream (/root/dash-dapp-autofaucet/node_modules/@dashevo/wallet-lib/src/plugins/Workers/TransactionSyncStreamWorker/methods/handleTransactionFromStream.js:13:34)
```

potentially the `1 utxo` error is fixed, but I never get to the point of actually sending a transaction so I can't test it.

**Comment by dash-maverick** [comment]
Hey @Alex-Werner @markin-io , chaining of transactions was supposed to help here. Could you please refer?
AFAIK lack of SPV support in DAPI has also impact here , correct @shumkov ?

**Comment by shumkov** [comment]
It doesn't related to SDK. More about chaining.

**Comment by dash-maverick** [comment]
there is something more in this, please take a look at the err log from Dashameter
https://gist.github.com/dashameter/5eb5a9fd0268684239b1dddfac02d452
